### ISSUE TITLE
suggestion: select multiple images and process them one by one

### ISSUE THREAD

**Issue by mordom0404** [Tw1ddle/geometrize#1]
suggestion: select multiple images and process them one by one

**Comment by Tw1ddle** [comment]
I'll post up a ChaiScript script that makes it easy to process multiple images one by one sometime soon 👍

**Comment by Tw1ddle** [comment]
Here's a simple script that will geometrize images in the directory as the app executable, one-by-one: https://pastebin.com/THnu9GxE

To use it, save images in the same directory as your Geometrize installation and run the script like this:
> ./Geometrize.exe --script_file="the/path/to/the/script/file/batch_image_geometrizer.chai"

To extend this, refer to this script that my twitter bot (https://twitter.com/Geometrizer) uses as that should give an idea of how it works. I find-replace the ::TOKENS:: in python to build a script in the bot, which obviously isn't done above: https://github.com/Tw1ddle/geometrize-twitter-bot/blob/master/script/geometrize_shape_choice_template.chai

The functions available to the scripts are defined here: https://github.com/Tw1ddle/geometrize/blob/master/geometrize/script/bindingscreator.cpp

**Comment by Tw1ddle** [comment]
I'll also make a tutorial video with more examples on how to do tasks like this using ChaiScript scripts at some point.
