### ISSUE TITLE
Random Desktop Icon

### ISSUE THREAD

**Issue by ProjectStickman** [Tw1ddle/geometrize#10]
This has been happening on 3 machines, with both windows 7 and 8, on every startup: The icon of the program always is completely random. Both as the shortcut on the desktop and also in the taskbar. This ranges from the GIMP icon, to games or even to the task manager.

**Comment by Tw1ddle** [comment]
Thanks, I'll look into it. Did you notice it happen with any other applications or just this one?

**Comment by ProjectStickman** [comment]
Only ever with this application. Literally none other, ever. Very odd.

**Comment by Tw1ddle** [comment]
Thanks. Annoyingly it's working OK on my Windows 10 PC (OS build 17134.706, version 1803).

I'll investigate on Windows 7 at somepoint, haven't noticed anything in my code or related bugs in Qt's issue tracker yet.

**Comment by Tw1ddle** [comment]
Did some testing, repro'd the issue, icon kept appearing empty/blank in the taskbar in my case.

I built Geometrize on my PC using Qt 5.12.3, and that build didn't appear to have the issue.

When AppVeyor adds Qt 5.12.3 to its Windows images I'll update my CI script to use it, and make a new release of the software :smile:

**Comment by Tw1ddle** [comment]
Hi, should be fixed now. Thanks for reporting it!

If you want, you can check this latest dev build to confirm that the icon's okay: https://geometrize-installer-bucket.s3.amazonaws.com/windows/msvc2015_64/geometrize_installer_240_25572935_msvc2015_64_release.exe
