### ISSUE TITLE
Batch processing

### ISSUE THREAD

**Issue by atlcell** [Tw1ddle/geometrize#12]
is there any way to run a batch on a folder of images using the GUI app?

**Comment by Tw1ddle** [comment]
Not at the moment, will look into adding that functionality soon though!

**Comment by atlcell** [comment]
@Tw1ddle next time you work on this, hop on a Twitch stream and let me work with you or something. I have some questions I want to ask the author, otherwise, I appreciate you so much for making this lib

**Comment by atlcell** [comment]
sent an email @Tw1ddle ;)

**Comment by Tw1ddle** [comment]
I've implemented this:

![Screenshot_20200419_070604](https://user-images.githubusercontent.com/1332318/79680847-4827ae80-820c-11ea-9f35-8e0c313e4c4f.png)

You can open via the "Open Task Queue" button on the launch page. You drag images files onto the list, then hit the "Run" button (or click an item on the list), causing the script on the right hand panel to run on the respective images.

The code for this widget is here: https://github.com/Tw1ddle/geometrize/blob/master/geometrize/dialog/taskqueuewindow.cpp

To get the software to do the particular batch processing you want, you have to customize the ChaiScript script in the script editor panel. The script bindings are defined here: https://github.com/Tw1ddle/geometrize/blob/master/geometrize/script/bindings/bindingscreator.cpp

A work in progress build is available here if you want to try it out: https://github.com/Tw1ddle/geometrize-installer#development-builds

I'll have a finalized version of all this in the next stable release of the software. Let me know if you have any questions or feedback!
