### ISSUE TITLE
New Builds

### ISSUE THREAD

**Issue by RafaelDominiquini** [Tw1ddle/geometrize#16]
Hi,

Why are there no new builds available here? The last one was in 2018. There are 133 commits since that build!

Thank you.

**Comment by jasoncharles** [comment]
Hi,
If you could produce a new build version that would be great.

Thanks

**Comment by Tw1ddle** [comment]
You can get more recent installers from CI here - these contain some WIP features and might be buggy: https://github.com/Tw1ddle/geometrize-installer#development-builds

I'm busy with private projects at the moment, will make new stable builds available eventually but don't know when yet.
