### ISSUE TITLE
how to use focus area script?

### ISSUE THREAD

**Issue by chris1683** [Tw1ddle/geometrize#19]
i try lot of different scripts to focus to a specific area...and all the times is crashing. do you have any documentation how to use it? thank you

**Comment by Tw1ddle** [comment]
No I'm afraid not. Many reasons it can crash, could be a typo in the script or a bug in the script engine itself. Post the script, image and the version of Geometrize you are using and I'll take a look.

No documentation, but script bindings for the latest trunk are defined here: https://github.com/Tw1ddle/geometrize/blob/master/geometrize/script/bindings/bindingscreator.cpp#L363 - the last time I did some development on this, I was getting the focus area script code working with a Wacom tablet and it was working ok

**Comment by Tw1ddle** [comment]
There are some ways it can crash if you have an error in your script, or edit the scripts while the scripting engines are running. When I make a new release I will make the scripts more user friendly.
