### ISSUE TITLE
A CLI would be appreciated

### ISSUE THREAD

**Issue by StoneCypher** [Tw1ddle/geometrize#20]
I would like to do some tooling to integrate several things.  

If your software offered a CLI, this would be much easier.

Do you think this would be practical?  I'd really appreciate it 😄

**Comment by StoneCypher** [comment]
For the record, I really enjoy your software

**Comment by Tw1ddle** [comment]
This might help: https://github.com/Tw1ddle/geometrize-lib-example - it's a bit more basic than the main Geometrize app but is a simple console program.

The main Geometrize application can also run ChaiScript scripts you pass it via the command line, but that's rather complicated to use - I used it for this Twitter bot though: https://github.com/Tw1ddle/geometrize-twitter-bot/blob/master/bot/geometrize.py#L14

Hope that helps!

**Comment by StoneCypher** [comment]
The library is exactly what I needed.  Thanks much
