### ISSUE TITLE
Low Dimensions

### ISSUE THREAD

**Issue by rovo79** [Tw1ddle/geometrize#21]
When I import a high resolution image, it always reduces it to a very low resolution.

How do you increase the size?

**Comment by junguler** [comment]
when you open the program where it shows sample thumbnails for images 
go to the file menu > global preferences > performance > un-check  image downscaling or increase it's value

**Comment by rovo79** [comment]
Thank you for that hint. I didn't realize that once I was in the rendering layout I had left behind a different File menu.
