### ISSUE TITLE
Max Threads

### ISSUE THREAD

**Issue by rovo79** [Tw1ddle/geometrize#22]
What aspect of the system are the threads based on?

Do you have an example of a safe number of threads you can go up to based on a CPU/GPU?

**Comment by Tw1ddle** [comment]
Hi, the calculations are all CPU-based.

Using more threads makes the shapes chosen more accurate, as each thread will independently try to find the best shape to add next.

If you set "Max threads" to 0 in the UI, it will default to using the same number of threads as cores in your PC, which is generally a good choice.

The code that uses this is here: https://github.com/Tw1ddle/geometrize-lib/blob/309b8f02ece6e3e29367d4c81c1213db76486025/geometrize/geometrize/model.cpp#L84

**Comment by rovo79** [comment]
Awesome, thanks for the clarity!
