### ISSUE TITLE
AppImage missing packages for Linux Mint 18.1

### ISSUE THREAD

**Issue by Jefficus** [Tw1ddle/geometrize#3]
Tried running the AppImage on my Linux Mint box and got the following complaints:

./geometrize_237.1_linux_g.-7.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by ./geometrize_237.1_linux_g.-7.AppImage)
./geometrize_237.1_linux_g.-7.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./geometrize_237.1_linux_g.-7.AppImage)

**Comment by Tw1ddle** [comment]
Thanks. This is because of https://github.com/Tw1ddle/geometrize-installer/issues/1

**Comment by Tw1ddle** [comment]
Hi, this should be fixed on Linux builds numbered 359 and above, here's a link to one: https://geometrize-installer-bucket.s3.amazonaws.com/linux/geometrize_359.1_linux_g%2B%2B-8.AppImage

I checked on a newly installed Linux Mint 18.1 VM and it ran for me. Let me know if you still have problems though.

One issue to note, the default folders for loading/saving images etc default to within the AppImage, which isn't how I meant it to be. I'll fix that at somepoint.
