### ISSUE TITLE
extremely high cpu load after 

### ISSUE THREAD

**Issue by wyroar** [Tw1ddle/geometrize#30]
i dont know much, and i recognise that high cpu load may be something that is expected of this program, but i basically put a png file in [attached]
![stareintocamerapfp](https://github.com/Tw1ddle/geometrize/assets/66280412/44b8debb-d829-412c-bec4-9856f785ae8d)

this lead to a much higher cpu load than normally happens the other times ive used this program
these were the settings i had at the time but it seems to work with other settings too
![image](https://github.com/Tw1ddle/geometrize/assets/66280412/4cae62ba-9b72-46e2-b863-208ad2691409)

i clicked start, it seemed to generate one object although i could not see it
my pc became extremely loud, i closed out of the window, it stayed loud, i opened task manager and closed the whole thing.

it was using 90% of my cpu, which is an AMD Ryzen 5 5600X 3.7 GHz 

https://github.com/Tw1ddle/geometrize/assets/66280412/3a1afa04-6783-470e-b75a-d2de20a60b17

6-Core Processor
here is a video of me replicating it. i installed the program today.

**Comment by Tw1ddle** [comment]
It would seem like your image is failing to load up from the beginning, but I am unable to repro the issue with that. Maybe try re-saving, renaming or moving the image somewhere else and trying again.

<img width="956" alt="image" src="https://github.com/Tw1ddle/geometrize/assets/1332318/a1ece17a-95c1-41c9-9a6b-8d9d28bbc28e">
