### ISSUE TITLE
Exporting a LOT of objects as a GIF

### ISSUE THREAD

**Issue by LOLIMHUMAN** [Tw1ddle/geometrize#31]
1. I generated 61K shapes (it looked beautiful :D) 
2. Luckily, I saved it as JSON, SVG and JPG first.
3. I've started exporting it as an animated GIF.
4. The app's become unresponsive, but the file was created and it's size has been gradually increasing.

That's what happened 3 days ago, and the app is still exporting it with breaks every night (I'm doing it on my laptop, so I just hibernate it). It's 15GiB large at this moment, any idea how long will it probably take to finish the exportation? Here's the generated JSON:
[YALPAP4-61K.json](https://github.com/Tw1ddle/geometrize/files/15015839/YALPAP4-61K.json)

**Comment by Tw1ddle** [comment]
It might never end, the GIF export option wasn't made with that many shapes in mind. I'd suggest you export images at different stages of the process and then combine them in another app like ScreenToGif

**Comment by LOLIMHUMAN** [comment]
Thx for the answer, I'll try it when I get home, but will exporting them in different stages set the start of the next GIF right after the previous one ends?
