### ISSUE TITLE
More Larger Size

### ISSUE THREAD

**Issue by dfggh0** [Tw1ddle/geometrize#32]
How can I modify the code to generate a larger size image?

**Comment by Tw1ddle** [comment]
If you go to the Preferences -> Performance tab, you can change the default size it scales the image to, the generation process will be slower for large images, hope that answers your question

![image](https://github.com/Tw1ddle/geometrize/assets/1332318/6620c5ee-589d-4756-ab7b-aeab082f0b43)

**Comment by dfggh0** [comment]
> If you go to the Preferences -> Performance tab, you can change the default size it scales the image to, the generation process will be slower for large images, hope that answers your question
> 
> ![image](https://private-user-images.githubusercontent.com/1332318/329883365-6620c5ee-589d-4756-ab7b-aeab082f0b43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MDIyOTMsIm5iZiI6MTcxNTYwMTk5MywicGF0aCI6Ii8xMzMyMzE4LzMyOTg4MzM2NS02NjIwYzVlZS01ODlkLTQ3NTYtYWI3Yi1hZWFiMDgyZjBiNDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTNUMTIwNjMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDY2NjVhZjMyOWMwNzdhNWNiODUyOGQ1Y2RjNWM3YjkwMWM2YThlMzgxYjRhMTM4NzQ4YTZhODU1NjQ2MTU3OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sf9appS-dCeSKWNtPqePf26F2UT8O9Yy83L29IYTUfA)

Thank you very much!I found it!!!

**Comment by pavelbat3** [comment]
Where is it? @dfggh0

**Comment by pavelbat3** [comment]
i cant find the preferences, maybe i am blind

**Comment by pavelbat3** [comment]
ive finally found it

**Comment by dfggh0** [comment]
> ive finally found it

Congratulations! I was too late.
