### ISSUE TITLE
Issue on Windows

### ISSUE THREAD

**Issue by Suleman-Elahi** [Tw1ddle/geometrize#4]
![image](https://user-images.githubusercontent.com/24384996/36409257-6b6fffb8-1630-11e8-8075-d1c2f82af621.png)

After installing, it is throwing this error ....

**Comment by Tw1ddle** [comment]
Looks like it's missing the Visual C++ redistributable for Visual Studio 2015, so you'll need to download/install this: https://www.microsoft.com/en-us/download/details.aspx?id=48145

I expected the windeployqt tool I use when packaging the installers would bundle that automatically, but   I guess not.

Thanks 👍
