### ISSUE TITLE
set background color for transparent png source file

### ISSUE THREAD

**Issue by jordangarside** [Tw1ddle/geometrize#6]
Is there any simple way for geometrize to allow setting a background color for transparent png images?

Currently it defaults to black.

![geometrized_image 2](https://user-images.githubusercontent.com/6321824/40868268-3e530428-65d9-11e8-943e-f6046969e8ea.png)

![medium 1](https://user-images.githubusercontent.com/6321824/40868271-42fc5772-65d9-11e8-9ed7-dca6c41b7d48.png)

Thanks!

**Comment by Tw1ddle** [comment]
Hi, don't think it's possible in the current desktop app, but I'll add controls to make images containing transparency easy to work with in a future release.

And yeah, looking at it I expect the main option you'd need is for the initial background color to be transparent rather than the average color of the target image.

**Comment by jordangarside** [comment]
That'd be great thanks.

For now I think I'll just use [sharp](https://github.com/lovell/sharp) to add a white background-color before piping the image through geometrize in node. The svg's will be displayed against a white background in my case for the near future.

**Comment by Tw1ddle** [comment]
I implemented this, added a couple of preferences to set the source file (i.e. target image) background and the starting background colour (see the two checkbox + color pickers):

![Screenshot_20200429_211517](https://user-images.githubusercontent.com/1332318/80642558-96378000-8a5e-11ea-84e1-7428a4027243.png)

Quickly tried it with the settings above, seems to work:

![result](https://user-images.githubusercontent.com/1332318/80642804-fe866180-8a5e-11ea-912d-5ae32226e48a.png)

Will be available in the CI builds shortly!

**Comment by Tmonitor745** [comment]
This does not seem to be available in the recent builds was it ever added?
