### ISSUE TITLE
Add shape limit option

### ISSUE THREAD

**Issue by Pichu0102** [Tw1ddle/geometrize#7]
An option to stop once a certain number of shapes has been reached would be nice.

**Comment by Tw1ddle** [comment]
Will add that soon. Probably by adding an scriptable stop condition, with a "stop if shape count >= n" as one of the preset scripts.

**Comment by Tw1ddle** [comment]
Hey, this is implemented! There's now a "Stop Conditions" tab next to the "Task Settings" and "Exporters" tabs when geometrizing an image.

This tab has a shape limit option and way to script custom stop conditions, will be in the latest automated builds soon: https://github.com/Tw1ddle/geometrize-installer#development-builds

Looks like this:

![](https://i.imgur.com/PQGEgvx.png)

**Comment by rovo79** [comment]
What is the difference between the Max Shape Count and the Custom Stop Condition?

**Comment by Tw1ddle** [comment]
In theory you could write other conditions for stopping the process, like if you reach a certain similarity to the desired image. I haven't documented how to do that yet though (or even tried it myself).

**Comment by rovo79** [comment]
I just allowed mine to up to 29,000+ shapes on a 1,200x 675 target image, when it was done, I almost couldn't tell the difference because it had pretty much recreated the image :)
