### ISSUE TITLE
Enable GPU

### ISSUE THREAD

**Issue by AntiMatterAMA** [Tw1ddle/geometrize#9]
Well the Title says it all. Please do something with OpenCL or whatever Nvidia GPUs use.  My CPU is at constant 80% - 90% while running the Program with standart settings. Picture is at 1000x488 and it draws with lines only. With OpenCl, it could be way faster (I think).

**Comment by Tw1ddle** [comment]
Thanks for the suggestion, GPU-based implementation would definitely speed things up a lot. It's something I'll do in a future project though, as it would be too much work to add to the current codebase.
